<?php
/**
 * Tasks to run during plugin uninstallation.
 *
 * @package product-swatches-light
 */

use ProductSwatchesLight\Plugin\Installer;

// if uninstall.php is not called by WordPress, die.
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

// prevent direct access.
defined( 'ABSPATH' ) || exit;

// do nothing if PHP-version is not 8.0 or newer.
if ( PHP_VERSION_ID < 80000 ) { // @phpstan-ignore smaller.alwaysFalse
	return;
}

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

// get constants.
require_once __DIR__ . '/inc/constants.php';

// run uninstallation.
Installer::get_instance()->remove_all_data( array( get_option( 'wc_' . LW_SWATCH_WC_SETTING_NAME . '_delete_on_uninstall', 0 ) ) );
